language: python
python:
  - "3.6" 
# command to install dependencies
install:
  - pip install -r src/homeeats/requirements.txt
# command to run tests
script:
  - cd src/homeeats/ && python3 manage.py test
