language: python
python:
  - "3.6" 
# command to install dependencies
install:
  - pip install -r src/homeeats/requirements.txt
# command to run tests
script:
  - cd src/homeeats/ && rm db.sqlite && python3 manage.py migrate --run-syncdb && python3 manage.py test
