# Generated by Django 2.2.6 on 2019-10-17 04:03

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('kitchen_license', models.CharField(max_length=30)),
                ('phone_number', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('password', models.CharField(default='', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('password', models.CharField(default='', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30)),
                ('cuisine', models.CharField(default='', max_length=30)),
                ('description', models.CharField(default='', max_length=200)),
                ('ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), default=list, size=None)),
                ('dish_image', models.ImageField(default='', upload_to='dishes')),
                ('cook_time', models.IntegerField(default=0)),
                ('cook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeeats_app.Cook')),
            ],
        ),
        migrations.CreateModel(
            name='Dish_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('description', models.CharField(max_length=200)),
                ('report_flag', models.BooleanField(default=False)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homeeats_app.Customer')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeeats_app.Dish')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(default='', max_length=60)),
                ('city', models.CharField(default='', max_length=60)),
                ('state', models.CharField(default='', max_length=20)),
                ('zipcode', models.CharField(default='', max_length=20)),
                ('cook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeeats_app.Cook')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeeats_app.Customer')),
            ],
        ),
    ]
