# Generated by Django 2.2.5 on 2019-10-31 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeeats_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish_review',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeeats_app.Customer'),
        ),
    ]
