# Generated by Django 2.2.5 on 2019-10-28 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeeats_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='cook',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='homeeats_app.Cook'),
        ),
        migrations.AlterField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='homeeats_app.Customer'),
        ),
    ]
