# Generated by Django 2.2.5 on 2019-10-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeeats_app', '0002_auto_20191028_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
