# Generated by Django 2.2.6 on 2019-10-17 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeeats_app', '0002_cook_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=30)),
                ('cook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeeats_app.Cook')),
            ],
        ),
        migrations.AlterField(
            model_name='dish',
            name='cuisine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeeats_app.Cuisine'),
        ),
    ]
