# Generated by Django 2.0.13 on 2019-10-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeeats_app', '0003_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='num_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dish',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
    ]
