# Generated by Django 2.2.5 on 2019-11-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeeats_app', '0003_auto_20191104_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='cook',
            name='delivery_distance_miles',
            field=models.IntegerField(default=30),
        ),
    ]
