# Generated by Django 2.2.6 on 2019-10-17 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeeats_app', '0003_auto_20191017_0440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cook',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cook',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='cook',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='cook',
            name='password',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
    ]
