# Generated by Django 2.2.6 on 2019-10-16 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeeats_app', '0004_auto_20191014_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='street_address',
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='address',
            name='street_name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='address',
            name='zipcode',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cook',
            name='phone_number',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default='', max_length=30),
        ),
    ]
