# Generated by Django 2.0.13 on 2019-10-28 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeeats_app', '0004_auto_20191028_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish_review',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeeats_app.Customer'),
        ),
    ]
