# Generated by Django 2.2.5 on 2019-11-05 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeeats_app', '0004_cook_delivery_distance_miles'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_cook_address',
            field=models.BooleanField(default=False),
        ),
    ]
