# Generated by Django 2.2.5 on 2019-11-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeeats_app', '0005_address_is_cook_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
