# Generated by Django 2.2.6 on 2019-11-10 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeeats_app', '0006_dish_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='allergies',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='dish',
            name='vegan',
            field=models.BooleanField(default=False),
        ),
    ]