# Generated by Django 2.2.5 on 2019-11-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeeats_app', '0007_auto_20191110_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuisine',
            name='flag',
            field=models.ImageField(default='', upload_to='flags'),
        ),
    ]
