# Generated by Django 2.2.5 on 2019-11-18 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeeats_app', '0009_cartitems_shoppingcart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItems',
            new_name='CartItem',
        ),
    ]
