# Generated by Django 2.2.5 on 2019-11-18 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeeats_app', '0011_auto_20191118_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='cook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeeats_app.Cook'),
        ),
    ]
