# Generated by Django 2.2.5 on 2019-11-19 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeeats_app', '0012_auto_20191118_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish_review',
            name='report_reason',
            field=models.CharField(choices=[('o', 'Offensive'), ('n', 'Not Relevant'), ('t', 'Threatening'), ('s', 'Spam')], default='', max_length=1),
        ),
    ]
