# Generated by Django 2.2.5 on 2019-11-21 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeeats_app', '0013_dish_review_report_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeeats_app.Dish_Review'),
        ),
    ]
