# Generated by Django 2.2.5 on 2019-11-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeeats_app', '0014_item_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='cook_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
