# Generated by Django 2.2.7 on 2019-11-23 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeeats_app', '0015_dish_cook_disabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
