# Generated by Django 2.2.7 on 2019-11-26 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeeats_app', '0017_auto_20191126_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_fee',
        ),
    ]
