# Generated by Django 2.2.7 on 2019-11-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeeats_app', '0018_remove_order_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='item_subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
