# Generated by Django 2.2.7 on 2019-11-29 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeeats_app', '0019_shoppingcart_item_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='current_customer_address',
            field=models.BooleanField(default=False),
        ),
    ]
