# Generated by Django 2.2.6 on 2019-12-02 07:10

from django.db import migrations, models
import homeeats_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('homeeats_app', '0021_shoppingcart_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pending_deadline',
            field=models.DateTimeField(default=homeeats_app.models.calculateTime),
        ),
    ]
