# Generated by Django 2.2.7 on 2019-12-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeeats_app', '0023_order_estimated_arrival_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='actual_arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
