# Generated by Django 2.2.7 on 2019-12-04 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeeats_app', '0024_order_actual_arrival_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='cook',
            name='banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='reject_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homeeats_app.RejectReason'),
        ),
    ]
