# Generated by Django 2.2.7 on 2019-12-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeeats_app', '0025_auto_20191204_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('c', 'Cooking'), ('o', 'Out For Delivery'), ('d', 'Delivered'), ('r', 'Rejected'), ('x', 'Customer Canceled')], default='p', max_length=1),
        ),
    ]
