# Generated by Django 2.2.6 on 2019-12-05 00:51

from django.db import migrations, models
import homeeats_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('homeeats_app', '0028_auto_20191204_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=homeeats_app.models.getOrderDate),
        ),
    ]
