# Generated by Django 2.2.7 on 2019-12-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeeats_app', '0029_auto_20191204_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='special_requests',
            field=models.CharField(default='', max_length=120),
        ),
    ]
