# Generated by Django 2.2.7 on 2019-12-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeeats_app', '0030_shoppingcart_special_requests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='total',
            new_name='total_before_tip',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='total_after_tip',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
