# Generated by Django 2.2.7 on 2019-12-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeeats_app', '0031_auto_20191205_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='cook',
            name='government_id',
            field=models.ImageField(default='', upload_to='cook_government_ids'),
        ),
    ]
