# Generated by Django 2.2.6 on 2019-12-05 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeeats_app', '0033_cookchangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookchangerequest',
            name='cook',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='homeeats_app.Cook'),
            preserve_default=False,
        ),
    ]
