# Generated by Django 2.2.7 on 2019-12-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeeats_app', '0035_auto_20191206_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='status',
            field=models.CharField(choices=[('a', 'Cash'), ('b', 'Card')], default='a', max_length=1),
        ),
    ]
