# Generated by Django 2.2.7 on 2019-12-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeeats_app', '0036_auto_20191208_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='status',
            new_name='payment_option',
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_option',
            field=models.CharField(choices=[('a', 'Cash'), ('b', 'Card')], default='a', max_length=1),
        ),
    ]
