# Generated by Django 2.2.6 on 2020-01-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeeats_app', '0037_auto_20191208_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='requested_delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
