# Generated by Django 2.2.6 on 2020-02-23 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import homeeats_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('homeeats_app', '0039_shoppingcart_requested_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.CreateModel(
            name='OrderMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=256)),
                ('time', models.DateTimeField(default=homeeats_app.models.getOrderDate)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeeats_app.Order')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
