# Generated by Django 2.2.6 on 2020-02-24 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeeats_app', '0040_auto_20200223_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
