# Generated by Django 2.2.7 on 2020-02-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeeats_app', '0041_auto_20200223_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cook_share',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='order',
            name='homeeats_share',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
