# Generated by Django 2.2.7 on 2020-03-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeeats_app', '0042_auto_20200226_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_image',
            field=models.ImageField(blank=True, default='', upload_to='dishes'),
        ),
    ]
