# Generated by Django 2.2.7 on 2020-03-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeeats_app', '0044_auto_20200326_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_image',
            field=models.ImageField(blank=True, null=True, upload_to='dishes'),
        ),
    ]
