# Generated by Django 2.2.6 on 2020-04-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeeats_app', '0046_auto_20200326_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='cook',
            name='offline_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cook',
            name='online_time',
            field=models.IntegerField(default=0),
        ),
    ]
